---
title: "Subjective status, Social Class and meritocracy perception"
linestretch: '1.5'          # interlineado
link-citations: yes         # citas linkeadas
fontsize: 12pt
linkcolor: blue
author:
- name: Julio Iturra ^[Corresponding author - jiturra@bigsss.uni-bremen.de]
  affiliation: Bremen International Graduate School of Social Sciences
- name: Juan Carlos Castillo
  affiliation: Universidad de Chile
bibliography: "input/bib/ess-merit.bib"
csl: "input/bib/apa6.csl"
css: "input/css/custom.css"
output:
  bookdown::html_document2:
    number_sections: false
  bookdown::word_document2:
    reference_docx: input/template.docx
    toc: false
    number_sections: false
  bookdown::pdf_document2:
    template: null
    toc: false
    keep_tex: false
    number_sections: false
    pandoc_args:
    - --template=input/mytemplate.tex #custom template para usar autores con afiliacion
geometry: margin=1in
header-includes:
  # - \usepackage[spanish,es-tabla,es-nodecimaldot]{babel} # para decimales con commas en vez de punto
  - \usepackage{times}           # Times New Roman
  - \usepackage{caption}
  - \hypersetup {colorlinks = true, linkcolor = blue, urlcolor = blue}  
  - \captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
lang: en-US
abstract: "Perceived meritocracy is understood as how societies describe the functioning of meritocracy, the ideal that promotes the distribution of resources in society based on individual effort and ability. Said this, are subjective and objective positions associated with perceived meritocracy? To what extent is objective position's influence on meritocracy perception moderated by subjective status? To answer these questions, we use nationally representative data from the 2018 wave of the Longitudinal Social Survey of Chile (N = 2,652). Regression analysis show that subjective social status has a robust positive association with perceived meritocracy, in line with the hypothesis. However, both positive and negative associations of income and occupational social class on perceived meritocracy were not confirmed. However, the hypothesis for education was confirmed, where higher educational attainment is associated with lower perceived meritocracy. Finally, we found that subjective status increases perceived meritocracy for those with higher incomes, tertiary education, and higher occupational social class."  
keywords: subjective social status, meritocracy perception, social class
classoption: a4paper
editor_options: 
  chunk_output_type: console
---

# Main Analysis
```{r figure02, fig.height=3, fig.width=10, fig.cap='Perceived meritocracy items'}
pacman::p_load(dplyr,sjPlot,ggplot2)
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1) 
options(ggplot2.discrete.colour = set1) 
ggplot2::theme_set(ggplot2::theme_bw()) 
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)

pacman::p_load(texreg,dplyr) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA
dfreg <- elsoc_w03 %>%
  dplyr::select(meffort,mtalent,merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()


 
 dat_likert_s1 <-
   dplyr::select(dfreg,meffort,mtalent)
 dat_likert_s1 <- sjmisc::rec(dat_likert_s1, rec="rev", append=FALSE)


     sjPlot::plot_likert(dplyr::select(dat_likert_s1,meffort_r,mtalent_r),
                         geom.colors = "PuBu",
                         geom.size = 0.8,
                         axis.labels = c("People are rewarded for their efforts",
                                         "People are rewarded for their intelligence and ability"),
                         cat.neutral = 3,
                         grid.range  =  c (1.2 , 1.2),
                         values  =  "sum.outside",
                         reverse.scale = F,
                         show.n = FALSE) +
       theme(legend.position="bottom") +
       ggplot2::scale_fill_manual(
         values = c("#b3b3b3ff", "#42A8BD", "#bdc9e1ff","#74a9cfff","#0570b0ff"),
         breaks=c("neutral",4,3,2,1),
         labels=c("Neither agree \nnor disagree","Strongly \ndisagree", "Disagree",
                     "Agree", "Strongly \nagree")) +
       labs(caption = paste0("Source: Authors calculation based on ELSOC 2018",
                             " (N = ",dim(dfreg)[1],")"))
     
ggsave(plot = last_plot(),filename = "figure002.png",path = here::here("output/images"),device = "png",units = "cm",width = 1,height = 0.3,scale = 25,dpi = 400)     
```


```{r figure03,  fig.cap='Correlation matrix between social status and perceived meritocracy', fig.height=8, fig.width=10, out.width='80%'}
pacman::p_load(texreg,dplyr) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA
dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()
df_corr<- dfreg %>% 
    dplyr::select(-sexo,-edad,-ponderador02) 
 cormat<- polycor::hetcor(data = df_corr,parallel = T)
 cormat <- as.matrix(cormat)

  diag(cormat) = NA #set diagonal values to NA
  # Set Row names of the matrix
  rownames(cormat) <- c("A. Meritocracy perception",
                        "B. Household income decile",
                        "C. Educational level",                        
                        "D. Subjective social status"
                        )
  #set Column names of the matrix
  colnames(cormat) <-c("(A)", "(B)","(C)","(D)")
  #Plot the matrix using corrplot
png(filename=here::here("output/images/figure003.png"),res = 300,
    width = 25,height = 25,units = "cm",family = "sans")
  corrplot::corrplot(cormat,
    method = "color",
    addCoef.col = "#000390",
    type = "upper",
    tl.col = "black",
    col=colorRampPalette(c("white","#0068DC"))(12),
    bg = "white",
    na.label = "-")
  text(3, 0.5, paste0("Source: Authors calculation based on ELSOC 2018",
                             " (N = ",dim(df_corr)[1],")"),   
       cex = 1)
dev.off()
```


# Regression analysis
```{r table01, echo=FALSE, results='asis'}
pacman::p_load(texreg,dplyr) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA

dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()

# dfreg$income <- car::Recode(dfreg$income,"1:4='Bottom40';5:9='middle50';10='top10'")
# dfreg$ess <- MLMusingR::group_center(x = dfreg$ess,grp = dfreg$income)

m_inc <- lm(merit~income,data = dfreg,weights = ponderador02)
m_educ <- lm(merit~edcine2,data = dfreg,weights =ponderador02)
m_status <- lm(merit~income+edcine2+ess+sexo+edad,data = dfreg,weights =ponderador02) 
m_inter_inc <- lm(merit~income*ess+edcine2+ess+sexo+edad,data = dfreg,weights =ponderador02)
m_inter_edu <-lm(merit~income+edcine2*ess+ess+sexo+edad,data = dfreg,weights =ponderador02) 
models <- list(m_inc,m_educ,m_status,m_inter_inc,m_inter_edu)
caption <- "Linear Regression for Perception of Meritocracy"

knitreg(
  l = models)

htmlreg(
  l = models,
  file = here::here("output/tables/table001.html"),
  caption = paste("Table 1:",caption),
  caption.above = T,
  custom.coef.map = list(
    income = "Income Decile",
    edcine2cine12 ="Primary & Lower secondary",
    edcine2cine34 = "Upper secondary",
    edcine2cine5 = "Short-cycle tertiary",
    edcine2cine678 = "Tertiary or higher",
    ess="Subjective Social Status",
    "income:ess" = "Income x SSS",
    "edcine2cine12:ess"= "Primary & Lower secondary x SSS",
    "edcine2cine34:ess"= "Upper secondary x SSS",
    "edcine2cine5:ess"= "Short-cycle tertiary x SSS",
    "edcine2cine678:ess"= "Tertiary or higher x SSS"
  ),
  groups = list("Education (ref: Incomplete Primary or less)"=2:5)
)
```

```{r figure04, fig.cap='Conditional effects of income decile by subjective social status on perceived meritocracy', fig.width=10, fig.height=5}
pacman::p_load(texreg,dplyr,marginaleffects,ggplot2) 
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(theme_minimal())
ggplot2::theme_update(text=element_text(size=15,  family="serif")) 

load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()
dfreg$income[dfreg$income=="99"] <- NA
dfreg$ess_cwc <- sjmisc::center(x = dfreg$ess)

ess_max<- mean(dfreg$ess) + sd(dfreg$ess)
ess_min<- mean(dfreg$ess) - sd(dfreg$ess)
ess_mea<- mean(dfreg$ess)

dfreg %>% na.omit()%>% group_by(income) %>% summarise(M=mean(ess),SDn=mean(ess)-sd(ess),SDp=mean(ess)+sd(ess))

m_inter_inc <- lm(merit~income*ess+edcine2+ess+sexo+edad,data = dfreg,weights=ponderador02)
df_pref <-
  predictions(
    m_inter_inc,newdata = datagrid(
      ess = c(ess_min, ess_mea, ess_max),
      income = 1:10,
      edcine2 = "cine34",
      sexo = "Female",
      edad = mean(dfreg$edad)
    )
  )


df_pref$ess <- as.factor(df_pref$ess)
df_pref %>% 
ggplot(aes(y=estimate,x=income, fill=ess,color=ess,ymin=conf.low, ymax=conf.high)) +
  geom_line(aes(y=estimate,x=income),size=0.75) +
  geom_point(size=2) +
  geom_ribbon(alpha=0.2,size=0.5,linetype=1) +
  scale_color_discrete(name="Sub.Status",labels = c("-1SD","Mean","+1SD")) +
  scale_fill_discrete(name="Sub.Status",labels = c("-1SD","Mean","+1SD"))+
   labs(y = "Perceived Meritocracy",x="Income Decile",) +
   ylim(2.5, 3.5) +
   scale_x_continuous(breaks = 1:10,labels = paste0("D",1:10)) +
   theme(legend.position="right",
         legend.direction = "vertical",
         axis.text=element_text(size=15),
         legend.background = element_blank(),
         legend.box.background = element_rect(colour = "black"))

ggsave(plot = last_plot(),filename = "figure004.png",path = here::here("output/images"),device = "png",units = "cm",width = 1,height = 0.5,scale = 25,dpi = 400) 
```

```{r named}
# # A tibble: 10 × 4
#    income     M   SDn   SDp
#     <dbl> <dbl> <dbl> <dbl>
#  1      1  3.80  2.00  5.59
#  2      2  4.04  2.48  5.60
#  3      3  3.99  2.40  5.58
#  4      4  4.30  2.86  5.75
#  5      5  4.12  2.57  5.67
#  6      6  4.35  2.98  5.72
#  7      7  4.43  3.05  5.82
#  8      8  4.61  3.17  6.05
#  9      9  4.64  3.25  6.03
# 10     10  5.56  4.29  6.83

df_pref_d01 <-
  predictions(
    m_inter_inc,newdata = datagrid(
      ess = c(2.00,3.80,5.59),
      income = c(1),
      edcine2 = "cine34",
      sexo = "Female",
      edad = mean(dfreg$edad)
    )
  )

df_pref_d01$ess <- car::recode(df_pref_d01$ess,"2.00=-1;3.80=0;5.59=1")

df_pref_d05 <-
  predictions(
    m_inter_inc,newdata = datagrid(
      ess = c(2.57,4.12,5.67),
      income = c(5),
      edcine2 = "cine34",
      sexo = "Female",
      edad = mean(dfreg$edad)
    )
  )
df_pref_d05$ess <- car::recode(df_pref_d05$ess,"2.57=-1;4.12=0;5.67=1")

df_pref_d10 <-
  predictions(
    m_inter_inc,newdata = datagrid(
      ess = c(4.29,5.56,6.83),
      income = c(10),
      edcine2 = "cine34",
      sexo = "Female",
      edad = mean(dfreg$edad)
    )
  )
df_pref_d10$ess <- car::recode(df_pref_d10$ess,"4.29=-1;5.56=0;6.83=1")

df_pref <- bind_rows(df_pref_d01,df_pref_d05,df_pref_d10)
df_pref$ess <- as.factor(df_pref$ess)
df_pref$income <- as.factor(df_pref$income)

df_pref %>% 
ggplot(aes(y=estimate,x=income, fill=ess,color=ess, group=ess,ymin=conf.low, ymax=conf.high)) +
 geom_errorbar(width = 0.1,position = "dodge")
```
      
```{r figure05, fig.cap='Conditional effects of Education by subjective social status on perceived meritocracy', fig.width=10, fig.height=5}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(theme_minimal())
ggplot2::theme_update(text=element_text(size=15,  family="serif")) 
pacman::p_load(texreg,dplyr,marginaleffects,ggplot2,stringr) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
elsoc_w03$ess_cwg <- MLMusingR::group_center(x = elsoc_w03$ess,elsoc_w03$edcine2)

dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess,ess_cwc,ess_cwg, sexo, edad,ponderador02) %>%
  na.omit()
# dfreg$ess_cwc <- mean(dfreg$ess) - dfreg$ess
ess_max<- mean(dfreg$ess) + sd(dfreg$ess)
ess_min<- mean(dfreg$ess) - sd(dfreg$ess)
ess_mea<- mean(dfreg$ess)
dfreg$income[dfreg$income=="99"] <- NA

dfreg %>% select(ess,ess_cwc,ess_cwg) %>% cor()

m_inter_edu <- lm(merit~income+edcine2*ess+ess+sexo+edad,data = dfreg,weights=ponderador02)
m_inter_edu2 <- lm(merit~income+edcine2*ess_cwc+ess_cwc+sexo+edad,data = dfreg,weights=ponderador02)
m_inter_edu4 <- lm(merit~income+edcine2*ess_cwg+ess_cwg+sexo+edad,data = dfreg,weights=ponderador02)

screenreg(list(m_inter_edu,m_inter_edu2,m_inter_edu4))
df_pref <-
  predictions(
    m_inter_edu,newdata = datagrid(
      ess = c(ess_min, ess_mea, ess_max),
      income = 5,
      edcine2 = levels(dfreg$edcine2),
      sexo = "Female",
      edad = mean(dfreg$edad)
    )
  )

df_pref <- as.data.frame(df_pref)
df_pref$ess <- as.factor(df_pref$ess)

df_pref$edcine2 <- factor(df_pref$edcine2,levels = ,labels = c("Incomplete Primary or less","Primary & Lower secondary","Upper secondary ","Short-cycle tertiary","Tertiary or higher"))

df_pref %>% 
ggplot(aes(y=estimate,x=edcine2, color=ess, group=ess,ymin=conf.low, ymax=conf.high)) +
  geom_line(size=0.75) +
  geom_point(size=2) +
  geom_errorbar(alpha=1,size=1,width=.1,linetype=1) +
  scale_color_discrete(name="Sub.Status",labels = c("-1SD","Mean","+1SD")) +
  scale_fill_discrete(name="Sub.Status",labels = c("-1SD","Mean","+1SD"))+
  labs(y = "Perceived Meritocracy",x="Education") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
     theme(legend.position="right",
         legend.direction = "vertical",
         axis.text=element_text(size=15),
         legend.background = element_blank(),
         legend.box.background = element_rect(colour = "black"))

ggsave(plot = last_plot(),filename = "figure005.png",path = here::here("output/images"),device = "png",units = "cm",width = 1,height = 0.5,scale = 25,dpi = 400) 
```


# (APPENDIX) Appendix {.unnumbered}

```{r}
 pacman::p_load(knitr, dplyr,haven, sjlabelled,vtable)
# Cargar base de datos procesada
  load(here::here("input/data/proc/elsoc_w03.RData"))
  elsoc_w03$meffort <-
   factor(elsoc_w03$meffort,
          levels = 1:5,
          labels = c("Strongly disagree","Disagree",
                     "Neither agree nor disagree", "Agree", "Strongly agree"))

  elsoc_w03$mtalent <-
   factor(elsoc_w03$mtalent,
          levels = 1:5,
          labels = c("Strongly disagree","Disagree",
                     "Neither agree nor disagree","Agree","Strongly agree"))

  elsoc_w03$edcine2 <-
   factor(elsoc_w03$edcine2,levels = levels(elsoc_w03$edcine2),
          labels = c("Incomplete Primary or lower","Primary & Lower secondary",
            "Upper secondary ","Short-cycle tertiary","Tertiary or higher"))
  elsoc_w03$edcine2 <- sjlabelled::set_label(elsoc_w03$edcine2,"Education")
  
  elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA
  elsoc_w03$inc10h <- sjlabelled::set_label(elsoc_w03$inc10h,"Income Decile")

  elsoc_w03$merit <- 
   (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2
  
  elsoc_w03$merit <- sjlabelled::set_label(elsoc_w03$merit,"Perceived meritocracy")
  df_desc<- elsoc_w03 %>%
    dplyr::select(merit,meffort,mtalent,
           ess,inc10h,edcine2,
           sexo,edad) %>% 
    dplyr::select(-meffort,-mtalent,
                  # -sexo,-edad,
                  # -ppolcat,-lngap_perc
                  )
  
  varlabs <- sjlabelled::get_label(df_desc) #recuperar labels
  df_desc <- na.omit(df_desc)

dfreg1 <- df_desc
varlab <- 
c("Perceived meritocracy","Subjective Social Status",
  "Household Income","Education",
  "Gender","Age")

sjlabelled::set_label(dfreg1) <- varlab

tabA1<- 
st(dfreg1,labels=T,
   title="Table A1: Descriptive Statistics for Study Variables",
   out = "kable",
   digits = 2, 
   factor.counts = F,
   factor.numeric = F,
   summ = list(
     c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)'),
     c('notNA(x)','mean(x)')
   ),
   summ.names = list(
     c('N','Mean','SD','Min','Max'),
     c('Count','Percent')   
   )) %>% kable_classic(html_font = "sans",full_width = F) 

kableExtra::save_kable(tabA1, here::here("output/tables/tableA01.html"))
```



# Supplementary Analysis

## Mediation

```{r tabS01}
pacman::p_load(texreg,dplyr,lavaan) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 
elsoc_w03$ess_cwc <- sjmisc::center(x = elsoc_w03$ess)
elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA
dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()

dfreg$edcine2 <- as.numeric(dfreg$edcine2)

med_model_cov <- '
  ess   ~ a*income + edad + sexo + edcine2
  merit ~ cprime*income + b*ess + edad + sexo + edcine2

  ind := a*b
  dir := cprime
  tot := ind + dir
'

mediation_income <- sem(
  med_model_cov, dfreg,
  estimator = "ML",
)
med_model_cov <- '
  ess   ~ a*edcine2 + edad + sexo + income 
  merit ~ cprime*edcine2 + b*ess + edad + sexo + income

  ind := a*b
  dir := cprime
  tot := ind + dir
'

mediation_educ <- sem(
  med_model_cov, dfreg,
  estimator = "ML",
)

custom.coef.map = list(
  "ess ~ income" = "SSS~Income",
  "ess ~ edcine2" = "SSS~Education",
  "merit ~ income" = "Merit~Income",
  "merit ~ edcine2" = "Merit~Education",
  "merit ~ ess" = "Merit~Subj.Status",
  "ind := a*b" = "Indirect",
  "dir := cprime" = "Direct",
  "tot := ind+dir" = "Total"
  )
screenreg(list(mediation_income,mediation_educ),digits = 3,
          custom.coef.map = custom.coef.map)


htmlreg(list(mediation_income,mediation_educ),digits = 3,
  file = here::here("output/tables/tableS01.html"),
  caption = paste("Table S1:","Mediation analysis for subjective social status, socioeconomic status and perceived meritocracy"),
  caption.above = T,custom.coef.map = custom.coef.map 
)
```

```{r}
pacman::p_load(texreg,dplyr) 
load(here::here("input/data/proc/elsoc_w03.RData"))
elsoc_w03$merit <- (as.numeric(elsoc_w03$meffort)+as.numeric(elsoc_w03$mtalent))/2 

elsoc_w03$inc10h[elsoc_w03$inc10h=="99"] <- NA

dfreg <- elsoc_w03 %>%
  dplyr::select(merit,income=inc10h, edcine2, ess, sexo, edad,ponderador02) %>%
  na.omit()

dfreg$ess_inc <- MLMusingR::group_center(x = dfreg$ess,grp = dfreg$income)
dfreg$ess_edu <- MLMusingR::group_center(x = dfreg$ess,grp = dfreg$edcine2)
dfreg$ess_gmc <- sjmisc::center(x = dfreg$ess)

m_status <- lm(merit~income+edcine2+sexo+edad+ess,data = dfreg,weights =ponderador02) 
m_status1 <- lm(merit~income+edcine2+ess_inc+sexo+edad,data = dfreg,weights =ponderador02) 
m_status2 <- lm(merit~income+edcine2+ess_edu+sexo+edad,data = dfreg,weights =ponderador02) 
m_status3 <- lm(merit~income+edcine2+ess_gmc+sexo+edad,data = dfreg,weights =ponderador02)
m_inter_inc <- lm(merit~income*ess+edcine2+ess+sexo+edad,data = dfreg,weights =ponderador02)
m_inter_edu <-lm(merit~income+edcine2*ess+ess+sexo+edad,data = dfreg,weights =ponderador02) 
models <- list(m_status,m_status1,m_status2,m_status3)
caption <- "Linear Regression for Perception of Meritocracy"

knitreg(
  l = models)
```


