---
title: "Preparación de datos"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: hide
    number_sections: yes
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
options(scipen=9999) # desactivar notacion cientifica
remove(list = ls()) #limpieza del entorno de trabajo
```

## Librerías

```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               car,         # recodificar variables
               sjlabelled,  # etiquetado de variables
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               summarytools,# resumen de dataframe
               stringr,     # manejo de vector de caracteres
               survey,      # diseno muestral complejo
               ggrepel,     # etiquetas en ggplo2
               tidyverse,    # ggplot2 + librerias complementarias
               mice
               )
```

## Datos

```{r}
load(file = here::here("input/data/original/ELSOC_W03_v1.00_R.RData"))
elsoc <- elsoc_2018
```


```{r}
for (i in 1:ncol(elsoc)) {
  elsoc[,i][elsoc[,i] == c(-888)]  <- NA #Missing 
  elsoc[,i][elsoc[,i] == c(-999)]  <- NA #Missing   
  }
```


# Variables

## Percepción meritocracia

```{r}
# Recodificación Variables meritocracia -----------------------------------#
elsoc$d05_01 <- sjlabelled::as_numeric(elsoc$d05_01)# Salir Adelante:
elsoc$d05_02 <- sjlabelled::as_numeric(elsoc$d05_02)# Salir Adelante:
elsoc$d05_03 <- sjlabelled::as_numeric(elsoc$d05_03)# Salir Adelante:
elsoc$d05_04 <- sjlabelled::as_numeric(elsoc$d05_04)# Salir Adelante:
elsoc$c18_09 <- sjlabelled::as_numeric(elsoc$c18_09)
elsoc$c18_10 <- sjlabelled::as_numeric(elsoc$c18_10) 

# Variables meritocracia promedio -----------------------------------------#
elsoc <- elsoc %>% mutate(salirad=(d05_02+d05_03+d05_04)/3) # Salir adelante
elsoc <- elsoc %>% mutate(recompe=(c18_09+c18_10)/2)        # Recompensa percibida
elsoc <- elsoc %>% mutate(recompe.sum=(c18_09+c18_10))      # Recompensa percibida suma

elsoc <- rename(elsoc,meffort=c18_09,mtalent=c18_10) # cambio de nombre

elsoc$meffort1 <- (elsoc$meffort -min(elsoc$meffort ))/(max(elsoc$meffort )-min(elsoc$meffort ))*100 #re-scale 1 a 5 -> 1 a 100
elsoc$mtalent1 <- (elsoc$mtalent -min(elsoc$mtalent ))/(max(elsoc$mtalent )-min(elsoc$mtalent ))*100 #re-scale 1 a 5 -> 1 a 100

elsoc$meffort <- ordered(elsoc$meffort)
elsoc$meffort3 <- car::recode(elsoc$meffort,recodes = "c(1,2)=1;3=2;c(4,5)=3")
elsoc$meffort3 <- factor(elsoc$meffort3,levels = 1:3,labels = c("Desacuerdo","Ni desacuerdo, Ni de acuerdo", "De acuerdo"),ordered = T)

elsoc$mtalent <- ordered(elsoc$mtalent)
elsoc$mtalent3 <- car::recode(elsoc$mtalent,recodes = "c(1,2)=1;3=2;c(4,5)=3")
elsoc$mtalent3 <- factor(elsoc$mtalent3,levels = 1:3,labels = c("Desacuerdo","Ni desacuerdo, Ni de acuerdo", "De acuerdo"),ordered = T)


sjlabelled::set_label(elsoc$meffort) <- "People are rewarded for their efforts"
sjlabelled::set_label(elsoc$mtalent) <- "People are rewarded for their intelligence and ability"
elsoc$meffort <- 
  sjlabelled::set_labels(elsoc$meffort,
                       labels = c("Strongly disagree"=1,"Disagree"=2,"Neither agree nor disagree"=3, "Agree"=4, "Strongly agree"=5)) 

elsoc$mtalent <- 
  sjlabelled::set_labels(elsoc$mtalent,
                       labels = c("Strongly disagree"=1,"Disagree"=2,"Neither agree nor disagree"=3, "Agree"=4, "Strongly agree"=5)) 
```

## Estatus subjetivo

```{r}
elsoc$ess      <- as.numeric(elsoc$d01_01) #Estatus Social Subjetivo
elsoc$essfam   <- as.numeric(elsoc$d01_02) #Estatus Social Subjetivo familiar
elsoc$esshijos <- as.numeric(elsoc$d01_03) #Estatus Social Subjetivo Hijos

sjlabelled::set_label(elsoc$ess) <- "Subjective Social Status"
```

## Brecha salarial percibida

```{r}
elsoc <- elsoc %>% rename("salperger"= d03_01,
                          "salperobr"= d03_02) 
  # mutate(salperobr=replace(salperobr, salperobr <= 40000  | salperobr>= 1000000, NA)) %>%
  # mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA))


elsoc$gap_perc   <-  as.numeric(elsoc$salperger/elsoc$salperobr) # brecha total
elsoc$lngap_perc <-  as.numeric(log(elsoc$gap_perc))             # brecha log

sjlabelled::set_label(elsoc$lngap_perc) <- "Perceived Salary Gap (ln)"
```

## Educación

```{r}
elsoc$edcine2 <- car::recode(elsoc$m01, "c(1,2)=1; c(3)=2;c(4,5)=3;c(6,7)=4;c(8,9,10)=5")
round(prop.table(table(elsoc$edcine2)), 3)

elsoc$edcine2 <- factor(elsoc$edcine2,
                        levels = c(1,2,3,4,5), 
                        labels=c("cine0",
                                 "cine12",
                                 "cine34",
                                 "cine5",
                                 "cine678"))
# c("Incomplete Primary or lower",
#    Primary & Lower secondary", 
#    Upper secondary ",
#    Short-cycle tertiary",
#    Tertiary or higher")

sjlabelled::set_label(elsoc$edcine2) <- "Educational level"
sjmisc::frq(elsoc$edcine2)
```

## Educación padres

```{r}
load(file = here::here("input/data/original/ELSOC_W01_v3.10.RData"))

elsoc_w1 <- elsoc_2016[,c("idencuesta","m27","m28")]
sjmisc::frq(elsoc_w1$m27)
sjmisc::frq(elsoc_w1$m28)

elsoc_w1$edpad <- car::recode(elsoc_w1$m27,"c(-888,-999)=NA;
                           c(1,2,3,4,5,6,7)=0;c(8,9,10)=1")
sjmisc::frq(elsoc_w1$edpad)

elsoc_w1$edmad <- car::recode(elsoc_w1$m28,"c(-888,-999)=NA;
                           c(1,2,3,4,5,6,7)=0;c(8,9,10)=1")
sjmisc::frq(elsoc_w1$edmad)

elsoc_w1$edfam_w1 <- if_else(is.na(elsoc_w1$edpad),
                             true = elsoc_w1$edmad,false = elsoc_w1$edpad)
sjmisc::frq(elsoc_w1$edfam_w1)

elsoc <- left_join(x = elsoc,y = elsoc_w1[,c("idencuesta","edfam_w1")] ) 


# wave 2018
elsoc$edpad <- elsoc$m27
sjmisc::frq(elsoc$edpad)
elsoc$edpad <- car::recode(elsoc$edpad,"c(-888,-999)=NA;
                           c(1,2,3,4,5,6,7)=0;c(8,9,10)=1")

sjmisc::frq(elsoc$edpad)

elsoc$edmad <- elsoc$m28
sjmisc::frq(elsoc$edmad)
elsoc$edmad <- car::recode(elsoc$edmad,"c(-888,-999)=NA;
                           c(1,2,3,4,5,6,7)=0;c(8,9,10)=1")

sjmisc::frq(elsoc$edmad)

elsoc$edfam <- if_else(is.na(elsoc$edpad),true = elsoc$edmad,false = elsoc$edpad) 
sjmisc::frq(elsoc$edfam)

elsoc$edfam <- if_else(is.na(elsoc$edfam),true = elsoc$edfam_w1,false = elsoc$edfam)
sjmisc::frq(elsoc$edfam)
elsoc$edfam <- sjlabelled::set_label(elsoc$edfam,"Parent with higher education")
```

## Autoridad y autonomia

```{r}
elsoc$m06 #En su trabajo, a cuantas personas supervisa usted? Convertir a numeric
elsoc$nempleados <- as.numeric(elsoc$m06)

elsoc$m10 #En su trabajo principal, tiene contrato de trabajo escrito?] [Estatus Contractual]
elsoc$contrato <- as.factor(elsoc$m10) #Colapsar 1 y 2 == Contrato,3 == Sin Contrato
elsoc$contrato <- car::recode(elsoc$contrato,
                              "c(1,2)='Has a contract';3='Does not have';
                              c(-888,-999)=NA;NA='Not apply'")

sjmisc::frq(elsoc$contrato)

elsoc$m07 #Relación de Empleo
sjmisc::frq(elsoc$m07)

elsoc$semp <- as.factor(elsoc$m07)
elsoc$semp <- car::recode(elsoc$semp, "c(4,5)=1;c(1,2,3,6,7)=2")
elsoc$semp <- factor(elsoc$semp,levels=c(1,2), labels=c("Autoempleo","Empleado"))
sjmisc::frq(elsoc$semp)
```

## Ocupación

```{r}
# Ocupación u oficio actual ISCO 88
elsoc$cod_m03
table(elsoc$cod_m03==9999)
elsoc$isco88 <- as.numeric(elsoc$cod_m03)
elsoc$isco88[elsoc$isco88==9999] <- NA
table(elsoc$isco88==9999)

table(elsoc$cod_m22==9999)
elsoc$cod_m22[elsoc$cod_m22==9999] <- NA
table(elsoc$cod_m22==9999)

elsoc$isco88 <- ifelse(is.na(elsoc$isco88),yes = as.numeric(elsoc$cod_m22),no = elsoc$isco88)
sjmisc::find_var(elsoc_2018,pattern = "hogar")
elsoc$isco08 <- elsoc$isco88 
table(elsoc$isco88==9999)


summary(as.numeric(elsoc$cod_m03))
summary(as.numeric(elsoc$cod_m22))
summary(as.numeric(elsoc$isco88))

# recodificar isco 08 a isco88 --------------------------------------------#
recode <- ("0110=0110;0210=0110;0310=0110;0100=0110;0200=0110;
0300=0110;1000=1000;
1100=1100;110=1100;1111=1110;1112=1120;1113=1130;1114=1140;1120=1210;1200=1200;
1210=1230;1211=1231;1212=1232;1213=1239;1219=1229;1220=1230;1221=1233;1222=1234;1223=1237;1300=1220;
1310=1221;1311=1221;1312=1221;1320=1220;1321=1222;1322=1222;1323=1223;1324=1235;1330=1236;1340=1229;1341=1229;1342=1229;1343=1229;1344=1229;1345=1229;1346=1227;1349=1229;
1400=1310;1410=1315;1411=1315;1412=1315;1420=1314;1430=1319;1431=1319;1439=1319;2000=2000;
2100=2100;2110=2110;2111=2111;2112=2112;2113=2113;2114=2114;2120=2120;2130=2210;2131=2211;2132=2213;2133=2200;2140=2140;2141=2149;2142=2142;2143=2149;2144=2145;2145=2146;2146=2147;2149=2149;2150=2140;2151=2143;2152=2144;2153=2144;2160=2140;2161=2141;2162=2141;2163=3471;2164=2141;2165=2148;2166=3471;2200=2200;
2210=2220;2211=2221;2212=2221;2220=2230;2221=2230;2222=2230;2230=3229;2240=3221;2250=2223;2260=3210;2261=2222;2262=2224;2263=2229;2264=3226;2265=3223;2266=3229;2267=3224;2269=2229;
2310=2310;2320=2320;2330=2320;2300=2300;2340=2330;2341=2331;2342=2332;2350=2350;2351=2351;2351=2352;2352=2340;2353=2359;2354=2359;2355=2359;2356=2359;2359=2359;2400=2400;
2410=2410;2411=2411;2412=2419;2413=2419;2420=2419;2421=2419;2422=2419;2423=2412;2424=2412;2430=2410;2431=2419;2432=2419;2433=3415;2434=3415;2500=2100;
2510=2130;2511=2131;2512=2131;2513=2131;2513=2139;2514=2132;2519=2131;2520=2131;2521=2131;2522=2131;2523=2131;2529=2139;2600=2400;
2610=2420;2611=2421;2612=2422;2619=2429;2620=2430;2621=2431;2622=2432;2630=2440;2631=2441;2632=2442;2633=2443;2634=2445;2635=2446;2636=2460;2640=2450;2641=2451;2642=2451;2643=2444;2650=2450;2651=2452;2652=2453;2653=2454;2654=2455;2655=2455;2656=3472;2659=3474;3000=3000;
3100=3100;3110=3110;3111=3111;3112=3112;3113=3113;3114=3114;3115=3115;3116=3116;3117=3117;3118=3118;3119=3119;3120=1220;3121=1229;3122=1222;3123=1223;3130=8160;3131=8161;3132=8163;3133=8150;3134=8155;3135=8120;3139=8290;3140=3210;3141=3211;3142=3212;3143=3212;3150=3140;3151=3141;3152=3142;3153=3143;3154=3144;3155=3145;3200=3100;
3210=3130;3211=3133;3212=3211;3213=3228;3214=7311;3220=3230;3221=3231;3222=3232;3230=3241;3240=3227;3250=3220;3251=3225;3252=3229;3253=3229;3254=3224;3255=3226;3256=3221;3257=3152;3258=3152;3259=3229;3300=3300;
3310=3410;3311=3411;3312=3419;3313=3433;3314=3434;3315=3417;3320=3410;3321=3412;3322=3415;3323=3416;3324=3421;3330=3420;3331=3422;3332=3414;3332=3439;3333=3423;3334=3413;3339=3429;3340=3430;3341=3431;3342=3431;3343=3431;3344=3431;3350=3440;3351=3441;3352=3442;3353=3443;3354=3444;3355=3450;3359=3449;3400=3400;
3410=3430;3411=3432;3412=3460;3413=3480;3420=3470;3421=3475;3422=3475;3423=3340;3423=3475;3430=3470;3431=3131;3432=3471;3433=3470;3434=5122;3435=3470;3500=3100;
3510=3120;3511=3122;3512=3121;3513=2139;3514=3121;3520=3130;3521=3130;3522=3114;3522=3132;4000=4000;
4110=4100;4120=4115;4100=4100;4130=4110;4131=4112;4132=4113;4200=4200;
4210=4210;4211=4211;4212=4213;4213=4214;4214=4215;4220=4220;4221=3414;4222=4222;4223=4223;4224=4222;4225=4222;4226=4222;4227=4190;4229=4222;4300=4100;
4310=4120;4311=4121;4312=4122;4313=4121;4320=4130;4321=4131;4322=4132;4323=4133;4400=4100;
4410=4140;4411=4141;4412=4142;4413=4143;4414=4144;4415=4141;4416=4190;4419=4190;5000=5000;
5100=5100;5110=5110;5111=5111;5112=5112;5113=5113;5120=5122;5130=5120;5131=5123;5132=5123;5140=5140;5141=5141;5142=5141;5150=5120;5151=5121;5152=5121;5153=9141;5160=5140;5161=5152;5162=5142;5163=5143;5164=5149;5165=3340;5169=5149;5200=5200;
5210=5230;5211=5230;5212=9111;5220=1314;5221=1314;5222=1314;5223=5220;5230=4211;5240=5220;5241=5210;5242=5220;5243=9113;5244=9113;5245=5220;5246=5123;5249=5220;5300=5100;
5310=5130;5311=5131;5312=5131;5320=5130;5321=5132;5322=5133;5329=5139;5400=5100;
5410=5160;5411=5161;5412=5162;5413=5163;5414=5169;5419=5169;6000=6000;
6100=6100;6110=6110;6111=6111;6112=6112;6113=6113;6114=6114;6120=6120;6121=6124;6122=6122;6123=6123;6129=6129;6130=6130;6210=6141;
6200=6150;6220=6150;6221=6151;6222=6152;6223=6153;6224=6154;6300=6200;
6310=6210;6320=6210;6330=6210;6340=6210;7000=7000;
7100=7100;7110=7120;7111=7129;7112=7122;7113=7113;7114=7123;7115=7124;7119=7129;7120=7130;7121=7131;7122=7132;7123=7133;7124=7134;7125=7135;7126=7136;7127=7240;7130=7140;7131=7141;7132=7142;7133=7143;7200=7200;7210=7210;
7211=7211;7212=7212;7213=7213;7214=7214;7215=7215;7220=7220;7221=7221;7222=7222;7223=7223;7224=7224;7230=7230;7231=7231;7232=7232;7233=7233;7234=7231;7300=7300;
7310=7310;7311=7311;7312=7312;7313=7313;7314=7321;7315=7322;7316=3471;7317=7331;7318=7332;7319=7330;7320=7340;7321=7340;7322=7340;7323=7345;7400=7200;
7410=7240;7411=7137;7412=7241;7413=7245;7420=7240;7421=7242;7421=7243;7422=7243;7500=7400;
7510=7410;7511=7411;7512=7412;7513=7413;7514=7414;7515=7415;7516=7416;7520=7420;7521=7421;7522=7422;7523=7423;7530=7430;7531=7434;7532=7435;7533=7436;7534=7437;7535=7441;7536=7442;7540=7200;7541=7216;7542=7112;7543=3152;7544=7143;7549=7000;8000=8000;
8100=8100;8110=8110;8111=7111;8112=8112;8113=8113;8114=8212;8120=8120;8121=8120;8122=8223;8130=8220;8131=8220;8132=8224;8140=8230;8141=8231;8142=8232;8143=8253;8150=8260;8151=8261;8152=8262;8153=8263;8154=8264;8155=8265;8156=8266;8157=8264;8159=8269;8160=8270;8170=8140;8171=8140;8172=8141;8180=8290;8181=8131;8182=8162;8183=8290;8189=8290;8200=8200;
8210=8280;8211=8281;8212=8283;8219=8290;8300=8300;
8310=8310;8311=8311;8312=8312;8320=8320;8321=8321;8322=8322;8330=8320;8331=8323;8332=8324;8340=8330;8341=8331;8342=8332;8343=8333;8344=8334;8350=8340;9000=9000;
9100=9100;9110=9130;9111=9131;9112=9132;9120=9140;9121=9133;9122=9142;9123=9142;9129=9140;9200=9200;
9210=9210;9211=9211;9212=9211;9213=9211;9214=9211;9215=9212;9216=9213;9300=9300;
9310=9310;9311=9311;9312=9312;9313=9313;9320=9320;9321=9322;9329=9320;9330=9330;9331=9331;9332=9332;9333=9333;9334=9333;9400=9100;
9410=9130;9411=5122;9412=9132;9500=9100;
9510=9120;9520=9112;9600=9100;
9610=9160;9611=9161;9612=9161;9613=9162;9620=9140;9621=9151;9622=9160;9623=9153;9624=9160;9629=9100;9999=0000")
class(elsoc$isco88)
elsoc$isco88 <- car::recode(elsoc$isco88,recodes = recode)
summary(elsoc$isco88)
```

## Clase Social (EGP)

```{r}
if (!require("occupar")) devtools::install_github("DiogoFerrari/occupar") # instalar pacman
# devtools::install_github("DiogoFerrari/occupar")
# If you don't want to update the dependencies, use: (you may need to install some dependencies manually)
# devtools::install_github("DiogoFerrari/occupar", dependencies=F)
library(magrittr)
library(tibble)
library(dplyr)
library(occupar)
## --------------------------------
## Converting from ISCO-A to ISCO-B
## --------------------------------
## The general format of the funcions are:
## isco<from>to<to> : convert from ISCO-<from> to ISCO-<to>, where <from> and <to> are the year identifying the ISCO
## isco<yr>labels   : get the labels for ISCO<yr>, where is  the year identifying the ISCO


## Example: Converting from ISCO-08 to ISCO-88
## -------------------------------------------
## suppose you have ISCO-08 codes (labels are not needed, only the codes; they are included for ilustration only):

## you can get a vector with corresponding ISCO-88 codes using:
elsoc$isco88b = occupar::isco08to88(elsoc$cod_m03)
View(elsoc[,c("isco88","isco88b")])
elsoc$testisco88 <- elsoc$isco88== elsoc$isco88b
table(elsoc$testisco88) #100% identicos


sjmisc::frq(elsoc$semp)
elsoc$selfemp <- ifelse(elsoc$semp=="Autoempleo",yes = 1,no = 0) 
sjmisc::frq(elsoc$selfemp)

elsoc$egp11<- isco88toEGP(elsoc$isco88, 
                          n.employees=elsoc$nempleados, 
                          self.employed=elsoc$selfemp,  
                          n.classes=11)
sjmisc::frq(elsoc$egp11)

elsoc$egp7<- isco88toEGP(elsoc$isco88, 
                          n.employees=elsoc$nempleados, 
                          self.employed=elsoc$selfemp,  
                          n.classes=7)
sjmisc::frq(elsoc$egp7)


elsoc %>% select(idencuesta,cod_m03,m03,cod_m22,m22,isco08,isco88,nempleados,selfemp,egp11,egp7) %>% 
  sjlabelled::write_stata(path = here::here("input/data/proc/ELSOC_ocup.dta"))


```

```{r egp-aplaza}
#Revisión de variables y renombrar variables
frq(elsoc$cod_m03) #CIUO
elsoc$isko<- elsoc$cod_m03
elsoc$isko <- occupar::isco08to88(elsoc$cod_m03)

frq(elsoc$m06) #Supervisión
elsoc$sv<-elsoc$m06

frq(elsoc$m07) #relación de empleo
#codificacion
#1.Empleado u obrero en empresa privada = 1. Employee
#2. Empleado u obrero del sector publico (incluso empresa publica o municipalidad)=1. Employee
#3.Miembro de las Fuerzas Armadas y de Orden=NA
#4.Patron/a o empleador/a (contrata o paga a honorarios a uno/o o mas trabajadores/as)=2. Self-employed
#5.Trabaja solo, no tiene empleados/as=2. Self-employed
#6.Familiar no remunerado=NA
#7.Servicio domestico=NA
elsoc$s<-car::recode(elsoc$m07, "1=1;2=1;3=NA;4=2;5=2;6:7=NA;-999:-888=NA")

# Fase 1: Codificación bruta en base a CIUO -------------------------------

#CODIGO BRUTO DE GANZEBOOM Y TREIMAN, ACÁ REQUIERE ALGUNAS MODIFICACIONES. SE SUGIERE LAS SIGUIENTES
#Profesores y Maestros (2320; 2331; 2332;2340;2351;2352;2359) = se modifican a rutina no manual (3) en vez de servicio II (2)
#Tenedores de libros (3433)=se modifican a rutina no manual (3) en vez de servicio II (2)
#vendedores ambulantes (9111; 9112;9113): Se modifican a trabajadores no calificados (9), en vez de trabajadores de rutina no manual


elsoc$egp<- car::recode(elsoc$isco88, 
                        "1000= 1;1100= 1;1110= 1;1120= 1;1130= 2;1140= 2;
                        1141= 2;1142= 2;1143= 2;1200= 1;1210= 1;1220= 1;1221=11;
                        1222= 1;1223= 1;1224= 1;1225= 1;1226= 1;1227= 1;1228= 1;
                        1229= 1;1230= 1;1231= 1;1232= 1;1233= 1;1234= 1;1235= 1;
                        1236= 1;1237= 1;1239= 1;1240= 2;1250= 1;1251= 1;1252= 2;
                        1300= 2;1310= 2;1311=11;1312= 2;1313= 2;1314= 2;1315= 2;
                        1316= 2;1317= 2;1318= 2;1319= 2;2000= 1;2100= 1;2110= 1;
                        2111= 1;2112= 1;2113= 1;2114= 1;2120= 1;2121= 1;2122= 1;
                        2130= 1;2131= 1;2132= 2;2139= 2;2140= 1;2141= 1;2142= 1;
                        2143= 1;2144= 1;2145= 1;2146= 1;2147= 1;2148= 2;2149= 1;
                        2200= 1;2210= 1;2211= 1;2212= 1;2213= 1;2220= 1;2221= 1;
                        2222= 1;2223= 1;2224= 1;2229= 1;2230= 2;2300= 2;2310= 1;
                        2320= 3;2321= 2;2322= 2;2323= 2;2330= 2;2331= 2;2332= 2;
                        2340= 2;2350= 1;2351= 1;2352= 1;2359= 2;2400= 1;2410= 2;
                        2411= 1;2412= 2;2419= 2;2420= 1;2421= 1;2422= 1;2429= 1;
                        2430= 2;2431= 2;2432= 2;2440= 1;2441= 1;2442= 1;2443= 1;
                        2444= 2;2445= 1;2446= 2;2450= 2;2451= 2;2452= 2;2453= 2;
                        2454= 2;2455= 2;2460= 2;3000= 2;3100= 2;3110= 2;3111= 2;
                        3112= 2;3113= 2;3114= 2;3115= 2;3116= 2;3117= 2;3118= 2;
                        3119= 2;3120= 2;3121= 2;3122= 2;3123= 2;3130= 2;3131= 2;
                        3132= 2;3133= 2;3139= 2;3140= 2;3141= 2;3142= 2;3143= 1;
                        3144= 1;3145= 2;3150= 2;3151= 2;3152= 2;3200= 2;3210= 2;
                        3211= 2;3212= 2;3213= 2;3220= 2;3221= 2;3222= 2;3223= 2;
                        3224= 2;3225= 2;3226= 2;3227= 2;3228= 2;3229= 2;3230= 3;
                        3231= 3;3232= 3;3240= 2;3241= 2;3242= 2;3300= 3;3310= 3;
                        3320= 3;3330= 3;3340= 3;3400= 2;3410= 2;3411= 2;3412= 2;
                        3413= 2;3414= 2;3415= 2;3416= 2;3417= 2;3419= 2;3420= 2;
                        3421= 2;3422= 2;3423= 2;3429= 2;3430= 3;3431= 2;3432= 2;
                        3433= 3;3434= 2;3439= 3;3440= 2;3441= 2;3442= 2;3443= 2;
                        3444= 2;3449= 2;3450= 2;3451= 2;3452= 7;3460= 3;3470= 2;
                        3471= 2;3472= 2;3473= 2;3474= 2;3475= 2;3480= 3;4000= 3;
                        4100= 3;4110= 3;4111= 3;4112= 3;4113= 3;4114= 3;4115= 3;
                        4120= 3;4121= 3;4122= 3;4130= 3;4131= 3;4132= 3;4133= 3;
                        4140= 3;4141= 3;4142= 9;4143= 3;4144= 3;4190= 3;4200= 3;
                        4210= 3;4211= 3;4212= 3;4213= 3;4214= 3;4215= 3;4220= 3;
                        4221= 3;4222= 3;4223= 3;5000= 3;5100= 3;5110= 3;5111= 3;
                        5112= 3;5113= 3;5120= 3;5121= 3;5122= 8;5123= 3;5130= 3;
                        5131= 3;5132= 3;5133= 3;5139= 3;5140= 8;5141= 8;5142= 3;
                        5143= 8;5149= 3;5150= 2;5151= 2;5152= 2;5160= 9;5161= 8;
                        5162= 8;5163= 9;5164= 8;5169= 9;5200= 3;5210= 3;5220= 3;
                        5230= 3;6000=10;6100=10;6110=10;6111=10;6112=10;6113=10;
                        6114=10;6120=10;6121=10;6122=10;6123=10;6124=10;6129=10;
                        6130=10;6131=11;6132=11;6133=11;6134=10;6140=10;6141=10;
                        6142=10;6150=10;6151=10;6152=10;6153=10;6154=10;6200=11;
                        6210=11;7000= 8;7100= 8;7110= 8;7111= 8;7112= 8;7113= 8;
                        7120= 8;7121= 9;7122= 9;7123= 9;7124= 8;7129= 8;7130= 8;
                        7131= 9;7132= 8;7133= 8;7134= 8;7135= 9;7136= 8;7137= 8;
                        7140= 8;7141= 8;7142= 9;7143= 9;7200= 8;7210= 8;7211= 8;
                        7212= 8;7213= 8;7214= 8;7215= 8;7216= 8;7220= 8;7221= 8;
                        7222= 8;7223= 8;7224= 8;7230= 8;7231= 8;7232= 8;7233= 8;
                        7234= 9;7240= 8;7241= 8;7242= 8;7243= 8;7244= 8;7245= 8;
                        7300= 8;7310= 8;7311= 8;7312= 8;7313= 8;7320= 9;7321= 9;
                        7322= 9;7323= 8;7324= 8;7330= 9;7331= 9;7332= 9;7340= 8;
                        7341= 8;7342= 8;7343= 8;7344= 8;7345= 8;7346= 8;7400= 8;
                        7410= 8;7411= 8;7412= 8;7413= 8;7414= 8;7415= 8;7416= 8;
                        7420= 8;7421= 9;7422= 8;7423= 8;7424= 9;7430= 8;7431= 9;
                        7432= 9;7433= 8;7434= 8;7435= 8;7436= 8;7437= 8;7440= 8;
                        7441= 8;7442= 8;7500= 8;7510= 7;7520= 8;7530= 9;8000= 9;
                        8100= 9;8110= 8;8111= 8;8112= 8;8113= 8;8120= 8;8121= 8;
                        8122= 8;8123= 8;8124= 8;8130= 9;8131= 9;8139= 9;8140= 9;
                        8141= 9;8142= 9;8143= 9;8150= 8;8151= 8;8152= 8;8153= 8;
                        8154= 8;8155= 8;8159= 8;8160= 8;8161= 8;8162= 8;8163= 8;
                        8170= 8;8171= 8;8172= 8;8200= 9;8210= 8;8211= 8;8212= 9;
                        8220= 9;8221= 9;8222= 9;8223= 9;8224= 9;8229= 9;8230= 9;
                        8231= 9;8232= 9;8240= 9;8250= 9;8251= 9;8252= 9;8253= 9;
                        8260= 9;8261= 9;8262= 9;8263= 9;8264= 9;8265= 9;8266= 9;
                        8269= 9;8270= 9;8271= 9;8272= 9;8273= 9;8274= 9;8275= 9;
                        8276= 9;8277= 9;8278= 9;8279= 9;8280= 9;8281= 9;8282= 9;
                        8283= 9;8284= 9;8285= 9;8286= 9;8290= 9;8300= 9;8310= 9;
                        8311= 8;8312= 9;8320= 9;8321= 9;8322= 9;8323= 9;8324= 9;
                        8330= 9;8331=10;8332= 8;8333= 8;8334= 9;8340= 9;8400= 9;
                        9000= 9;9100= 3;9110= 3;9111= 3;9112= 3;9113= 3;9120= 9;
                        9130= 9;9131= 9;9132= 9;9133= 9;9140= 9;9141= 9;9142= 9;
                        9150= 9;9151= 9;9152= 9;9153= 9;9160= 9;9161= 9;9162= 9;
                        9200= 9;9210=10;9211=10;9212=10;9213=10;9300= 9;9310= 9;
                        9311= 9;9312= 9;9313= 9;9320= 9;9321= 9;9322= 9;9330= 9;
                        9331= 9;9332= 9;9333= 9 ")

sjmisc::frq(elsoc$egp)
# Fase 2: Codificación eb base a situación de empleo o situación d --------

#promocionalidad de ciertas ocupaciones
elsoc$p<-car::recode(elsoc$isko, "1000:9299=1; else=0")
#degradabilidad de ciertas ocupaciones
elsoc$d<-car::recode(elsoc$isko, "1300:1319=1;3400:3439=1;5000:5230=1;else=0")

#Nueva variables
elsoc$egp11<-elsoc$egp
#SI EGP="'IIIa Routine non-manuals" Y Supervisa a más de una persona, ENTONCES EGP= "II Lower controllers"
elsoc$egp11[elsoc$egp==3 & elsoc$sv>=1]<-2
#SI EGP="'IIIa Routine non-manuals" Y es autoempleado Y tiene degradez, ENTONCES EGP="'IIIb Lower sales-service'"                  
elsoc$egp11[elsoc$egp==3 & elsoc$s==2 & elsoc$d==1]<-4
#SI EGP>="V Manual supervisors" Y EGP<="VIIa Unskilled workers" Y es autoempleado Y tiene promocionalidad, ENTONCES EGP="'IVa Self-empl. with empl."
elsoc$egp11[elsoc$egp==2 & elsoc$s==2 & elsoc$d==1]<-4
#SI EGP>="V Manual supervisors" Y EGP<="VIIa Unskilled workers" Y es autoempleado Y tiene promocionalidad, ENTONCES EGP="'IVa Self-empl. with empl."
elsoc$egp11[elsoc$egp>=7 & elsoc$egp<=9  & elsoc$s==2 & elsoc$p==1]<-5
#SI EGP= VI Skilled workers' Y Supervisa a más de una persona, ENTONCES EGP= "V Manual supervisors' 
elsoc$egp11[elsoc$egp==8 & elsoc$sv>=1]<-7
#SI EGP= 'VIIb Farm labors Y es autoempleado, ENTONCES, EGP="IVc Self-empl. farmers"                   
elsoc$egp11[elsoc$egp==10 & elsoc$s==2]<-11
#SI EGP= 'IIIb Lower sales-service Y supervisa a menos de una persona, ENTONCES EGP= 'IVa Self-empl. with emp
elsoc$egp11[elsoc$egp==4 & elsoc$sv<1]<-5 #EN ORIGINAL SALE QUE DEBE SER "MENOS DE", PERO ESTO ES CONTRATEORICO
#SI EGP= IVa Self-empl. with empl.  Y supervisa desde una persona, ENTONCES, EGP= 'IIIb Lower sales-service'           
elsoc$egp11[elsoc$egp==5 & elsoc$sv>=1]<-4
#SI EGP= II Lower controllers' y supervisa a más de 10 personas, entonces EGP= I Higher controllers'                    
elsoc$egp11[elsoc$egp==2 & elsoc$sv>=10]<-1
#SI EGP= 'IIIa Routine non-manuals'' y supervisa a más de 10 personas, entonces EGP= I Higher controllers'
elsoc$egp11[elsoc$egp==3 & elsoc$sv>=10]<-1
#SI EGP= 'IIIb Lower sales-services' y supervisa a más de 10 personas, entonces EGP= I Higher controllers'                   
elsoc$egp11[elsoc$egp==4 & elsoc$sv>=10]<-1

table(elsoc$egp11)
elsoc$egp11<-as.integer(elsoc$egp11)

elsoc$egp_f<-
  car::recode(elsoc$egp11, 
              "1='I Higher controllers';2='II Lower controllers';3='IIIa routine non-manuals';
              4='IVa Self-empl. with empl.'; 5='IVb Self-empl. no empl.';7='V Manual supervisors';
              8='VI Skilled workers'; 9='VIIa Unskilled workers';
              10='VIIb Farm labors'; 11='IVc Self-empl. farmers';
              100='Armed Force'; c(2470,7139,8287)=NA", as.factor=T,
              levels=c("I Higher controllers",
                       "II Lower controllers",
                       "IIIa routine non-manuals",
                       "IVa Self-empl. with empl.",
                       "IVb Self-empl. no empl.",
                       "V Manual supervisors",
                       "VI Skilled workers",
                       "VIIa Unskilled workers",
                       "VIIb Farm labors",
                       "IVc Self-empl. farmers", 
                       "Armed Force"))

table(elsoc$egp_f)
prop.table(table(elsoc$egp_f))
sjmisc::frq(elsoc$egp_f)

#revision para imputación
table(elsoc$egp_f,elsoc$m02)

#NOTA: ELSOC no es representativa de sectores rurales, por lo que se recomienda alguna de las siguientes agregaciones del esquema EGP
#colapsar version de 7 clases
elsoc$egp_7<- 
  car::recode(elsoc$egp_f, 
              "'I Higher controllers'='I Upper service class';
              'II Lower controllers'='II Lower service class';
              c('IIIa routine non-manuals')='III routine non-manuals';
              c('IVa Self-empl. with empl.','IVb Self-empl. no empl.', 'IVc Self-empl. farmers')= 'IVa+b+c petty bourgeoisie';
              'V Manual supervisors'='V Technicians and supervisors';
              'VI Skilled workers'='VI Skilled workers';
              c('VIIa Unskilled workers','VIIb Farm labors')='VII Unskilled workers'")


table(elsoc$egp_7)
prop.table(table(elsoc$egp_7))
sjmisc::frq(elsoc$egp_7)

#colapsar version de 5 clases

elsoc$egp_5<-car::recode(elsoc$egp_7, "c('I Upper service class','II Lower service class')='I+II Service Class';
                             'IVa+b+c petty bourgeoisie'='IV Petty Bourgeoisie';
                             c('VI Skilled workers','VII Unskilled workers')='VI+VII Manual Class'")

table(elsoc$egp_5)
prop.table(table(elsoc$egp_5))
sjmisc::frq(elsoc$egp_5)

elsoc$egp_5b<-car::recode(elsoc$egp_7, 
                          "c('I Upper service class','II Lower service class')='I+II Service Class';
                          'IVa+b+c petty bourgeoisie'='IV Petty Bourgeoisie';
                          c('V Technicians and supervisors','VI Skilled workers')='V+VI Skilled workers';
                          c('VII Unskilled workers')='VIIab Unskilled workers'")


table(elsoc$egp_5b)
prop.table(table(elsoc$egp_5b))
sjmisc::frq(elsoc$egp_5b)

#colapsar version de 4 clases

elsoc$egp_4<-car::recode(elsoc$egp_7, "c('I Upper service class','II Lower service class')='I+II Service Class';
                             c('III routine non-manuals','V Technicians and supervisors')='IIIa Intermediate class';
                             'IVa+b+c petty bourgeoisie'='IV Petty Bourgeoisie';
                             c('VI Skilled workers','VII Unskilled workers')='VI+VII Manual Class'")

table(elsoc$egp_4)
prop.table(table(elsoc$egp_4))
sjmisc::frq(elsoc$egp_4)


elsoc$egp_4b<-car::recode(elsoc$egp_7, 
                          "c('I Upper service class','II Lower service class')='I+II Service Class';
                          'IVa+b+c petty bourgeoisie'='IV Petty Bourgeoisie';
                          c('V Technicians and supervisors','VI Skilled workers','VII Unskilled workers')='V+VI+VII Manual workers'")

table(elsoc$egp_4b)
prop.table(table(elsoc$egp_4b))
sjmisc::frq(elsoc$egp_4b)

name_isko<- elsoc %>% select(starts_with("egp_")) %>% names()
for (i in name_isko) {
  elsoc[[i]] <- forcats::fct_rev(elsoc[[i]])
}
```

```{r egp-isko}
# Cargar base con Esquema EGP ---------------------------------------------#
egp01 <- 
  sjlabelled::read_stata(path = 
                           here::here("input/data/proc/ELSOC_egp-isei-siops.dta"))
egp01 <- egp01 %>% dplyr::select(idencuesta,egpisko=egp,isei,siops)

elsoc <- left_join(elsoc,egp01,"idencuesta") #Pegar ELSOC con EGP 
# egplab  <- sjlabelled::get_labels(elsoc$egp) # Etiquetas de clase EGP10
# egptlab <- sjlabelled::get_labels(elsoc$egptorche) # Etiquetas de clase EGP7
# egp10   <- sjlabelled::get_labels(elsoc$egp) # Etiquetas de clase EGP7

# Esquema de 11 categorias
sjmisc::frq(elsoc$egpisko)
elsoc$egpisko <- 
  sjlabelled::set_labels(elsoc$egpisko,
                         labels =  
                           c("Service Class Higher (I)", 
                             "Service Class Lower (II)", 
                             "Routine non-manual (III)",
                             "Self-employed with employees (IV.a)",
                             "Self-employed with no empoyees (IV.b)",
                             "Manual supervisors/Lower grade technicians (V)", 
                             "Skilled manual workers (VI)" ,
                             "Semi & unskilled workers (VII.a)",
                             "Farmers and other workers in primary production (VII.b)",
                             "Peasants and small agricultural landowners (IV.c)"))

sjmisc::frq(elsoc$egpisko)

# Esquema trabajadores urbanos y rurales----------------------------------------

# Esquema de 07 categorias, incluye trabajadores rurales
elsoc$egpisko07 <- car::recode(var = elsoc$egpisko,
                               recodes = "3=3;c(4,5)=4;7=5;8=6;c(9,10,11)=7") 

sjmisc::frq(elsoc$egpisko07)
elsoc$egpisko07 <-
  factor(elsoc$egpisko07,
                         labels = 
                           c("Service high (I)",
                           "Service low (II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Manual supervisors/Lower grade technicians (V)",
                           "Skilled manual workers (VI)",
                           "Operators (VII.ab, IVc)"))

sjmisc::frq(elsoc$egpisko07)

# Esquema de 06 categorias, incluye trabajadores rurales
# se colapsan Supervisores manuales con calificados manuales(V+VI)
elsoc$egpisko06 <- car::recode(var = elsoc$egpisko,
                               recodes = "3=3;c(4,5)=4;c(7,8)=5;c(9,10,11)=6") 

sjmisc::frq(elsoc$egpisko06)
elsoc$egpisko06 <-
  factor(elsoc$egpisko06,
                         labels = 
                           c("Service high (I)",
                           "Service low (II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Skilled Manual workers (V+VI)",
                           "Operators (VII.ab, IVc)"))

sjmisc::frq(elsoc$egpisko06)

# Esquema de 05 categorias, incluye trabajadores rurales
# se colapsan  Servicios Alto y Bajo (I+II)
# se colapsan Supervisores manuales con calificados manuales(V+VI)
elsoc$egpisko05<- car::recode(var = elsoc$egpisko,
                               recodes = "c(1,2)=2;3=3;c(4,5)=4;c(7,8)=5;c(9,10,11)=6")

sjmisc::frq(elsoc$egpisko05)
elsoc$egpisko05 <-
  factor(elsoc$egpisko05,
                         labels = 
                           c("Service (I+II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Skilled Manual workers (V+VI)",
                           "Operators (VII.ab, IVc)"))
# sjmisc::frq(elsoc$egpisko05)
# elsoc$egpisko05 <-
#   factor(elsoc$egpisko05,levels =
#       c("Operators (VII.ab, IVc)","Skilled Manual workers (V+VI)",
#   "Small owners and Self-employed (IV.ab)","Routine non-manual (III)",
#   "Service (I+II)"))

sjmisc::frq(elsoc$egpisko05)

# Esquema trabajadores urbanos-------------------------------------------------
# Esquema de 07 categorias, excluye trabajadores rurales
elsoc$egpisko07ur <- car::recode(var = elsoc$egpisko,
                               recodes = "3=3;c(4,5)=4;7=5;8=6;c(9)=7;c(10,11)=NA")

sjmisc::frq(elsoc$egpisko07ur)

elsoc$egpisko07ur <-
  factor(elsoc$egpisko07ur,
                         labels = 
                           c("Service high (I)",
                           "Service low (II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Manual supervisors/Lower grade technicians (V)",
                           "Skilled manual workers (VI)",
                           "Semi & unskilled workers (VII.a)"))

sjmisc::frq(elsoc$egpisko07ur)

# Esquema de 06 categorias, excluye trabajadores rurales
# se colapsan Supervisores manuales con calificados manuales(V+VI)
elsoc$egpisko06ur <- car::recode(var = elsoc$egpisko,
                               recodes = "3=3;c(4,5)=4;c(7,8)=5;c(9)=6;c(10,11)=NA") 

sjmisc::frq(elsoc$egpisko06ur)
elsoc$egpisko06ur <-
  factor(elsoc$egpisko06ur,
                         labels = 
                           c("Service high (I)",
                           "Service low (II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Skilled Manual workers (V+VI)",
                           "Semi & unskilled workers (VII.a)"))

sjmisc::frq(elsoc$egpisko06ur)

# Esquema de 05 categorias, excluye trabajadores rurales
# se colapsan  Servicios Alto y Bajo (I+II)
# se colapsan Supervisores manuales con calificados manuales(V+VI)
elsoc$egpisko05ur<- car::recode(var = elsoc$egpisko,
                               recodes = "c(1,2)=2;3=3;c(4,5)=4;c(7,8)=5;c(9)=6;c(10,11)=NA")

sjmisc::frq(elsoc$egpisko05ur)
elsoc$egpisko05ur <-
  factor(elsoc$egpisko05ur,
                         labels = 
                           c("Service (I+II)",
                           "Routine non-manual (III)",
                           "Small owners and Self-employed (IV.ab)",
                           "Skilled Manual workers (V+VI)",
                           "Semi & unskilled workers (VII.a)"))

sjmisc::frq(elsoc$egpisko05ur)

# Esquema de 04 categorias, 
# se colapsan  Servicios Alto y Bajo (I+II)
# se colapsan Supervisores manuales con calificados manuales (V+VI) + Operators (VIIa.b,IVc)



name_isko<- elsoc %>% select(starts_with("egpisko")) %>% names()
for (i in name_isko) {
  elsoc[[i]] <- forcats::fct_rev(elsoc[[i]])

}
```

```{r egp-latam}
source(file = "production/prod_egp-respondent.R") #class scheme - respondent
source(file = "production/prod_egp-household.R")#class scheme - head household 

#if NA in class of respondent, replace with household

sjmisc::frq(elsoc$clase11e)
sjmisc::frq(elsoc$clase11h)
elsoc$class11 <- ifelse(is.na(elsoc$clase11e),elsoc$clase11h,elsoc$clase11e)
sjmisc::frq(elsoc$class11)

# if NA in respondents it is assumed to be lower than head of household
# know, with the cases in we have information for respondent and head of household
# we replace the value by the highest one, just for those

# Replace the highest class by dominance criteria 
# Keep the highest of two values:
elsoc$class11d <- pmax(elsoc$class11, #social class respondent + household vs:
                       elsoc$clase11h,#social class household
                       na.rm = T) # if NA, do nothing

elsoc$class11d <- sjlabelled::set_labels(elsoc$class11d,labels = sjlabelled::get_labels(elsoc$clase11e)) 
sjmisc::frq(elsoc$class11d)
elsoc_w03$class11d <- elsoc$class11d

# Class Scheme 3 classes
elsoc_w03$class3 <- car::recode(elsoc_w03$class11d ,as.factor = T,
                            levels =c('Service Class (I+II)',
                                      'Intermediate class (III+IV)',
                                      'Working Class (V+VI+VII)'), 
                            "1:2='Service Class (I+II)';
                             3:7='Intermediate class (III+IV)';
                             8:11='Working Class (V+VI+VII)'")
sjmisc::frq(elsoc_w03$class3)



# Class Scheme 6 classes
elsoc_w03$class6 <- car::recode(
  elsoc_w03$class11d,
  as.factor = T,
  levels = c(
    'Service class (I - higher grade)',
    'Service class (II - lower grade)',
    'Routine non-manual (IIIa+b)',
    'Petty-bourgeoise (IVa+b+c)',
    'Skilled manual workers and supv. (V+VI)',
    'Non-skilled manual workers (VIIa+b)'
  ),
  "1='Service class (I - higher grade)';
   2='Service class (II - lower grade)';
   3:4='Routine non-manual (IIIa+b)';
   5:7='Petty-bourgeoise (IVa+b+c)';
   8:9='Skilled manual workers and supv. (V+VI)';
   10:11='Non-skilled manual workers (VIIa+b)'"
)

# Class Scheme 6 classes
elsoc_w03$class5 <- car::recode(
  elsoc_w03$class11d,
  as.factor = T,
  levels = c(
    'Service class (I - II)',
    'Routine non-manual (IIIa+b)',
    'Petty-bourgeoise (IVa+b+c)',
    'Skilled manual workers and supv. (V+VI)',
    'Non-skilled manual workers (VIIa+b)'
  ),
  "1:2='Service class (I - II)';
   3:4='Routine non-manual (IIIa+b)';
   5:7='Petty-bourgeoise (IVa+b+c)';
   8:9='Skilled manual workers and supv. (V+VI)';
   10:11='Non-skilled manual workers (VIIa+b)'"
)

sjmisc::frq(elsoc_w03$class6)
```


## Ingreso del hogar

```{r}
# Pareto corrected formula  (Hout, 2004)--------------------------------------#
Ltop_1<- 1850001
Ltop  <- 2700000

ftop_1 <- 14
ftop   <- 10

V  = (log(ftop_1 + ftop) - log(ftop)) / (log(Ltop) -log(Ltop_1))
M_top = 0.5* Ltop *(1+(V/(V-1))) # = $ 3.726.106

elsoc$mean_tramos[elsoc$m30==1] <-110000
elsoc$mean_tramos[elsoc$m30==2] <-250000.5
elsoc$mean_tramos[elsoc$m30==3] <-305000.5
elsoc$mean_tramos[elsoc$m30==4] <-355000.5
elsoc$mean_tramos[elsoc$m30==5] <-400000.5
elsoc$mean_tramos[elsoc$m30==6] <-445000.5
elsoc$mean_tramos[elsoc$m30==7] <-490000.5
elsoc$mean_tramos[elsoc$m30==8] <-535000.5
elsoc$mean_tramos[elsoc$m30==9] <-585000.5
elsoc$mean_tramos[elsoc$m30==10]<-640000.5
elsoc$mean_tramos[elsoc$m30==11]<-700000.5
elsoc$mean_tramos[elsoc$m30==12]<-765000.5
elsoc$mean_tramos[elsoc$m30==13]<-845000.5
elsoc$mean_tramos[elsoc$m30==14]<-935000.5
elsoc$mean_tramos[elsoc$m30==15]<-1040000.5
elsoc$mean_tramos[elsoc$m30==16]<-1180000.5
elsoc$mean_tramos[elsoc$m30==17]<-1375000.5
elsoc$mean_tramos[elsoc$m30==18]<-1670000.5
elsoc$mean_tramos[elsoc$m30==19]<-2275000.5
elsoc$mean_tramos[elsoc$m30==20]<-M_top
table(elsoc$mean_tramos)

elsoc$m29 <- ifelse(test = (is.na(elsoc$m29)),yes = elsoc$mean_tramos,no = elsoc$m29)
summary(elsoc$m29)

elsoc <- rename(elsoc, inghogar=m29, nhogar=m54) 
elsoc$ingneto   <- as.numeric(elsoc$inghogar/elsoc$nhogar) # ingreso neto
elsoc$lningneto <- log(elsoc$ingneto)                      # logaritmo del ingreso neto


#---Ingresos individuales ---------------------------------------------------#
#Remplazar NA por media de categorías Ingreso -------------------------------#

summary(elsoc$m13) # Ingreso individual; NA = 1716
summary(elsoc$m14) # Ingreso individual por tramos

Ltop_1<- 850001
Ltop  <- 1300001 

ftop_1 <- 16
ftop   <- 9

V  = (log(ftop_1 + ftop) - log(ftop)) / (log(Ltop) -log(Ltop_1))
M_top = 0.5* Ltop *(1+(V/(V-1))) # = $1.762.784

elsoc$mean_tramos.ind <- NA
elsoc$mean_tramos.ind[elsoc$m14 == 1]  <- 40000
elsoc$mean_tramos.ind[elsoc$m14 == 2]  <- 62501
elsoc$mean_tramos.ind[elsoc$m14 == 3]  <- 105001
elsoc$mean_tramos.ind[elsoc$m14 == 4]  <- 147501
elsoc$mean_tramos.ind[elsoc$m14 == 5]  <- 190001
elsoc$mean_tramos.ind[elsoc$m14 == 6]  <- 220001
elsoc$mean_tramos.ind[elsoc$m14 == 7]  <- 255001
elsoc$mean_tramos.ind[elsoc$m14 == 8]  <- 300001
elsoc$mean_tramos.ind[elsoc$m14 == 9]  <- 340001
elsoc$mean_tramos.ind[elsoc$m14 == 10] <- 380001
elsoc$mean_tramos.ind[elsoc$m14 == 11] <- 432501
elsoc$mean_tramos.ind[elsoc$m14 == 12] <- 502501
elsoc$mean_tramos.ind[elsoc$m14 == 13] <- 602501
elsoc$mean_tramos.ind[elsoc$m14 == 14] <- 757501
elsoc$mean_tramos.ind[elsoc$m14 == 15] <- 1075001
elsoc$mean_tramos.ind[elsoc$m14 == 16] <- M_top
table(elsoc$mean_tramos.ind)
elsoc$m13 <- ifelse(test = (is.na(elsoc$m13)),yes = elsoc$mean_tramos.ind,no = elsoc$m13)
summary(elsoc$m13) # NA = 1523

elsoc$ingreso <- as.numeric(elsoc$m13)

#---Deciles (ingreso individual)-----------------------------------------------#
elsoc <- elsoc %>% mutate(inc10 = ntile(ingreso, 10)) #Crear Deciles de ingreso
elsoc$inc10 <- car::recode(elsoc$inc10, "NA=99") #Deciles de ingreso + "no responde"
elsoc$D10 <- factor(elsoc$inc10, levels = c(1,2,3,4,5,6,7,8,9,10,99), 
                    labels = c("D01","D02","D03","D04","D05",
                               "D06","D07","D08","D09","D10","No responde"));table(elsoc$D10)



#---Deciles (ingreso per capita hogar)-----------------------------------------#
elsoc <- elsoc %>% mutate(inc10h = ntile(ingneto, 10)) #Crear Deciles de ingreso neto
elsoc$inc10h <- car::recode(elsoc$inc10h, "NA=99") #Deciles de ingreso + "no responde"
elsoc$D10h <- factor(elsoc$inc10h, levels = c(1,2,3,4,5,6,7,8,9,10,99), 
                    labels = c("D01","D02","D03","D04","D05", 
                               "D06","D07","D08","D09","D10","No responde"));table(elsoc$D10h)



elsoc <- elsoc %>% mutate(inc05h = ntile(ingneto, 5)) #Crear Quintiles de ingreso neto
elsoc$inc05h <- car::recode(elsoc$inc05h, "NA=99") #Deciles de ingreso + "no responde"
elsoc$Q05h <- factor(elsoc$inc05h, levels = c(1,2,3,4,5,99), 
                     labels = c("Q01","Q02","Q03","Q04","Q05","No responde"));table(elsoc$Q05h)
```

## Sexo, Edad, Política

```{r}
#---Sexo----#
elsoc$sexo <- car::recode(elsoc$m0_sexo, "1=1;2=0")
elsoc$sexo <- factor(elsoc$sexo, levels = c(0,1), labels = c("Male","Female")) #Sexo
sjlabelled::set_label(elsoc$sexo) <- "Gender"


#---Edad----#
elsoc$edad  <- as.numeric(elsoc$m0_edad) #Edad
sjlabelled::set_label(elsoc$edad) <- "Age"
elsoc$edad2 <-elsoc$edad^2 

#---Posición Política----#
elsoc$ppolcat  <- car::recode(elsoc$c15, "c(0,1,2,3,4)=1;5=2;c(6,7,8,9,10)=3;11=4;12=5") 
elsoc$ppolcat  <- factor(elsoc$ppolcat, levels = c(1,2,3,4,5), labels = c("Left/Center-Left",
                                                      "Center",
                                                      "Right/Center-Right",
                                                      "Independent",
                                                      "None"))

sjlabelled::set_label(elsoc$ppolcat) <- "Left-Right Position"
#---Estatus laboral---#
estlabels <- c("Full time",
               "Partial",
               "Study and work",
               "Study",
               "Retired",
               "Unemployed /active ",
               "Reproductive work",
               "Unable to work (sick or disabled)",
               "Not Working/Not active")

elsoc$estlab <-  factor(elsoc$m02,levels = c(1:9),labels = estlabels)

sjlabelled::set_label(elsoc$estlab) <- "Labor status"

#---numero de hijos---#
summary(elsoc$m37_01)
summary(elsoc$m37_02)
elsoc$nhijos <- elsoc$m37_01 + elsoc$m37_02
table(elsoc$nhijos)
elsoc$nhijos[is.na(elsoc$nhijos)] <- 0
```

# Imputación

```{r, cache=TRUE}
set.seed(1234)
data02 <- elsoc %>% dplyr::select(inghogar,"edcine2","egpisko","sexo","edad","edad2","ess","region","estlab","estrato")

imp1 <- mice(data02, m = 5)
dat.imp1<- complete(imp1)
summary(dat.imp1$inghogar)

summary(complete(imp1,1)$inghogar)
summary(complete(imp1,2)$inghogar)
summary(complete(imp1,3)$inghogar)
summary(complete(imp1,4)$inghogar)
summary(complete(imp1,5)$inghogar)


# - guardamos el promedio del ingreso imputado de las 5 bases en data02 
data02$fit.mimp <-(complete(imp1,1)$inghogar+complete(imp1,2)$inghogar+complete(imp1,3)$inghogar+complete(imp1,4)$inghogar+complete(imp1,5)$inghogar)/5
summary(data02$fit.mimp)

#check de missing
data02$inghogar.imp <- ifelse(test = is.na(data02$inghogar),
                              yes = data02$fit.mimp,
                              no = data02$inghogar) 

#calcular ingreso percapita del hogar
elsoc$inghogar.imp <- data02$inghogar.imp 
elsoc$ingneto.imp <- elsoc$inghogar.imp/elsoc$nhogar
summary(elsoc$ingneto.imp)


elsoc <- elsoc %>% mutate(inc10.imp = ntile(elsoc$inghogar.imp, 10)) 

#crear deciles y quintiles de ingreso percapita del hogar
elsoc <- elsoc %>% mutate(inc10h.imp = ntile(ingneto.imp, 10)) 
elsoc <- elsoc %>% mutate(inc05h.imp = ntile(ingneto.imp, 5)) 
elsoc$inc05h.imp <- factor(elsoc$inc05h.imp,levels = 1:5,
                           labels = c("Q01","Q02","Q03","Q04","Q05"))


sjlabelled::set_label(elsoc$inc10h.imp) <- "Household Income Decile"
sjlabelled::set_label(elsoc$inc10.imp) <- "Household Income Decile"
```

```{r}
# IPW para mercado laboral-----------------------------------------------#
# Dummy mercado trabajo | dentro = 0, fuera =1
elsoc$work <-
  ifelse(test = (elsoc$estlab %in% c("jornada_completa",
                                     "jornada_parcial",
                                     "estudia_trabaja")),
         yes = 0,
         no = 1)
table(elsoc$work)
prop.table(table(elsoc$work))

prop01 <- glm(work~sexo+edad+edad2+edcine2+region+ess,data = elsoc,family = "binomial",na.action = na.exclude)
summary(prop01)
summary(prop01$fitted.values)

elsoc$prob <- predict.glm(object = prop01,newdata = elsoc[,c("sexo","edad","edad2","edcine2","region","ess","nhijos")],type = "response")

# En base a esto : http://sites.utexas.edu/prc/files/IPWRA.pdf
# * Revisar:
  # https://stats.stackexchange.com/questions/411711/why-do-stabilized-ipw-weights-give-the-same-estimates-and-ses-as-unstabilized-we
  # http://www.rebeccabarter.com/blog/2017-07-05-ip-weighting/

summary(elsoc$work/elsoc$prob + (1-elsoc$work)/(1-elsoc$prob)) # weights segun clases de LM (inferencia causal)

elsoc$ipw01 <- ifelse(test = (elsoc$work ==1),yes = (1/elsoc$prob),no = 1/ (1-elsoc$prob))
summary(elsoc$ipw01)

(elsoc$work) / (elsoc$prob)         # Treated = 1 = Fuera de mercado laboral
(1 - elsoc$work) / (1 - elsoc$prob) # Control = 0 = Dentro de mercado laboral

elsoc$ipw_s <- ifelse(test = (elsoc$work ==1),yes = (elsoc$work) / (elsoc$prob),no = (1 - elsoc$work) / (1 - elsoc$prob))
summary(elsoc$ipw_s) # stabilized ipw


table(elsoc$ipw_s>7.463204)
table(elsoc$ipw_s<1.038734)

elsoc$ipw_s[elsoc$ipw_s>7.463204] <- 7.463204
elsoc$ipw_s[elsoc$ipw_s<1.038734] <- 1.038734
summary(elsoc$ipw_s)

#- Ver P99 y remplazara todos los que sean > valor
#- ver P01 y remplazar todos los que sean <  valor
```

```{r}
elsoc_w03 <- elsoc %>% dplyr::select(idencuesta,ponderador02,region,
                                     meffort3,mtalent3,
                                     ess,lngap_perc,edcine2,edfam,
                                     starts_with("egpisko"),isei,siops,
                                     starts_with("egp_"),
                                     # egp_4,egp_4b,
                                     # egp_5,egp_5b,egp_7,
                                     contrato,
                                     inc10.imp,
                                     inc10h.imp,inc05h.imp,
                                     meffort,mtalent,recompe.sum,recompe,
                                     sexo,edad,edad2,
                                     ppolcat,estlab,ipw01,ipw_s,Q05h)
```

# Guardar datos

```{r}
# Generar codebook
sjPlot::view_df(x = elsoc_w03,
                show.frq = T,
                show.prc = T,
                file = here::here("output/codebook_ess-merit.html")
                )


# Guardar datos en RData
save(elsoc_w03,file = here::here("input/data/proc/elsoc_w03.RData"))
```
